### ISSUE TITLE
Error property "AllowedSortOrders" does not exist in the XML namespace 

### ISSUE THREAD

**Issue by it19862** [DevExpress-Examples/how-to-bind-to-infiniteasyncsource#8]
VS - 2017

Error property "AllowedSortOrders" does not exist in the XML namespace "http://schemas.devexpress.com/winfx/2008/xaml/grid". Line 17 position 53. InfiniteAsyncSourceSample MainWindow.xaml

![2019-02-23_10-18-26](https://user-images.githubusercontent.com/18245828/53283247-63a44000-3754-11e9-914e-bafb2bf7265f.png)

**Comment by AndreyMarten** [comment]
Hello,

I see that you are referencing our assemblies **v17.2**, while features illustrated in this example are available starting with **v18.1** (that is why this example's branch is 18.1.2+). You need to upgrade your controls in this project to resolve this issue. You can use the [Project Converter](https://documentation.devexpress.com/ProjectConverter/2529/Project-Converter) tool for this. 

Should you face any difficulties with this, please feel free to create a corresponding ticket in our [Support Center](https://www.devexpress.com/Support/Center/Question/Create). 

Thanks,
Andrey
